---
title: "mylab1"
author: "Nathaniel Burola"
date: "1/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rlang)
library(fansi)
library(tidyverse)
library(here)
library(janitor)
library(kableExtra)
```

#Read in NOAA_fisheries.csv data 
```{r}
us_landings <- read_csv(here("data", "noaa_fisheries.csv"))
```

#Now make a tidy version of the data frame:
```{r}
landings_tidy <- us_landings %>% 
  janitor::clean_names() %>% #clean_names() converts column names into lowercase 
  mutate(state = str_to_lower(state), #Mutuate will create a new column called state which  is a lowercase version of the state 
         afs_name = str_to_lower(afs_name)) %>% #Straight to lower command will rewrite words
  mutate(dollars_num = parse_number(dollars_usd)) #Parse will drop any non-numeric characters before or after the first number 
```

#Let us get some information for salmon 
```{r}
salmon_landings <- landings_tidy %>% 
  mutate(afs_clean = str_remove(afs_name, pattern = "aggregate")) #The word aggregate has become removed 
  filter(str_detect(afs_clean, pattern = "shark"))
  seperate(afs_c)
  
```

